### ISSUE TITLE
error with dependencies

### ISSUE THREAD

**Issue by gg4u** [rholder/csv2es#19]
I installed it but:

Traceback (most recent call last):
```
  File "/usr/local/bin/csv2es", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Python/2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 2671, in <module>
    working_set.require(__requires__)
  File "/Library/Python/2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 654, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Python/2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: urllib3==1.10.2
```

despite urllib3 is present (1.19.1)

how to fix it?  Maybe upgrading requirements? Also, pip install will uninstall most recent versions of dependencies - which I manually restailled to latest versions.

**Comment by ThachNgocTran** [comment]
I met this problem, too. Tried to reinstall urllib but then it said the library was already installed. Then, reinstalled csv2es and everything was ok again.
