### ISSUE TITLE
csv2es.py AttributeError

### ISSUE THREAD

**Issue by jaune-rouge** [rholder/csv2es#22]
I'm using Python 3 from Anaconda, and have created the potatoes example csv file. I am able to create the potatoes index, but it won't load the data. I've tried different csv files and indexes, and still get the same. I get the following error:

> Traceback (most recent call last):
  File "/anaconda/bin/csv2es", line 11, in <module>
    sys.exit(cli())
  File "/anaconda/lib/python3.6/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/anaconda/lib/python3.6/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda/lib/python3.6/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/csv2es.py", line 211, in cli
    perform_bulk_index(host, index_name, doc_type, documents, docs_per_chunk, bytes_per_chunk, parallel)
  File "/anaconda/lib/python3.6/site-packages/csv2es.py", line 107, in perform_bulk_index
    bytes_per_chunk=bytes_per_chunk))
  File "/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 652, in __call__
    for function, args, kwargs in iterable:
  File "/anaconda/lib/python3.6/site-packages/csv2es.py", line 104, in <genexpr>
    delayed(local_bulk)(host, index_name, doc_type, chunk)
  File "/anaconda/lib/python3.6/site-packages/pyelasticsearch/utils.py", line 31, in bulk_chunks
    for action in actions:
  File "/anaconda/lib/python3.6/site-packages/csv2es.py", line 57, in all_docs
    fieldnames = doc_file.next().strip().split(delimiter)
AttributeError: '_io.BufferedReader' object has no attribute 'next'

**Comment by jaune-rouge** [comment]
Edit: It would seem that that's just a python 3.6 issue. As in 2.7 I'm not getting the error, but a different one about the delimiter needing to be a 1-character string.
